name: learn-github-actions
on: 
  push:
    branches:
      - main
jobs:
  clone_src:
    runs-on: ubuntu-20.04 
		steps:
      - run: echo "Hello"
			- uses: actions/checkout@v3
			- run: |
				ls -al
				cd .github/workflows/
				ls -al
